language: python
python:
    - "2.7"

install:
    - pip install -U platformio

script:
    - platformio ci janitoo/ --lib=libraries --board=megaatmega1280
    - platformio ci janitoo/ --lib=libraries --board=uno
    - platformio ci janitoo/ --lib=libraries --board=due
    - platformio ci janitoo/ --lib=libraries --board=teensy31
    - platformio ci janitoo/ --lib=libraries --board=esp01
    - platformio ci janitoo/ --lib=libraries --board=esp01
